chore: make the script work without Nix

diff --git a/bin/sync-data b/bin/sync-data
--- a/bin/sync-data
+++ b/bin/sync-data
@@ -1,4 +1,34 @@
 #!/usr/bin/env bash
 
-curl -L https://api.github.com/repos/bastengao/chinese-holidays-data/tarball \
-  | tar -xvz --strip-components=2  --directory=priv/data --wildcards '*/data/*'
+if ! command -v curl > /dev/null 2>&1; then
+    echo "command 'curl' not found"
+    exit 1
+fi
+
+if ! command -v tar > /dev/null 2>&1; then
+    echo "command 'tar' not found"
+    exit 1
+fi
+
+TAR_VERSION_INFO=$(tar --version)
+TAR_VARIANT=
+if echo "$TAR_VERSION_INFO" | grep -i GNU > /dev/null 2>&1; then
+    TAR_VARIANT="GNU"
+elif echo "$TAR_VERSION_INFO" | grep -i BSD > /dev/null 2>&1; then
+    TAR_VARIANT="BSD"
+else
+    echo "unknown tar variant"
+    exit 1
+fi
+
+case $TAR_VARIANT in
+    GNU)
+        curl -L https://api.github.com/repos/bastengao/chinese-holidays-data/tarball \
+            | tar -xvz --strip-components=2  --directory=priv/data --wildcards '*/data/*'
+        ;;
+
+    BSD)
+        curl -L https://api.github.com/repos/bastengao/chinese-holidays-data/tarball \
+            | tar -xvf - --strip-components=2 -C priv/data --include='*/data/*'
+        ;;
+esac
